version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: igd-elasticsearch-test
    restart: unless-stopped
    ports:
      - "9200:9200"
    volumes:
      - ./elastic-backup:/usr/share/elasticsearch/backup
      - ./es-data:/usr/share/elasticsearch/data
    tty: true
    environment:
      - cluster.name=igd-es-cluster
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/backup
      - "ES_JAVA_OPTS=-Xms512m -Xmx2012m"
